import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Providers as ChakraProvider } from '../providers/chakraProvider'; 
import { Providers as WalletProvider } from '../providers/walletProvider'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <body className={inter.className}>
            <ChakraProvider>
              <WalletProvider>
                {children}
              </WalletProvider>
            </ChakraProvider>
          </body>
        </html>
      
  )
}
